### PR TITLE
set darkness method added

### PR DESCRIPTION
**Pull request by JianDk**
added set darkness method which basically is ~SDXX in ZPL language.

### CODE REVIEW

**Comment by cod3monk** [comment]
Please add a check that non valid values will raise an exception (assertion is okay).

**Comment by cod3monk** [comment]
Are you certain that single digits are valid for this command? I understand from the ZPL2 Documentation only double digits (`00` instead of `0`) are acceptable values, similar to your previous docstring.

**Comment by JianDk** [comment]
Hello Julian,

Yes, I just gave it a test trying with 0. There I get a blank label. Afterwards, I tried with 28 and got the label with the desired darkness level. Perhaps double digits is not strict necessary? 

Best regards,
Jian

**Comment by cod3monk** [comment]
good enough for me :)

Thanks!

**Pull request merged**
