### PR TITLE
Add code128 barcode type ^BC

### PR DESCRIPTION
**Pull request by qdelcourte**
**Support of code128**

Docs:
https://support.zebra.com/cpws/docs/zpl/code_128.htm
https://www.servopack.de/support/zebra/ZPLII-Prog.pdf p.67

### CODE REVIEW

**Comment by cod3monk** [comment]
Thanks for the PR! Would you like me to bump the version up and make a release including this PR?

**Comment by qdelcourte** [comment]
It's no hurry. But yes if you could include the last 3 PR it'll be great

**Comment by cod3monk** [comment]
Included all three PRs in v0.1.8.

**Comment by qdelcourte** [comment]
Thanks!

**Pull request merged**
